from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
urlpatterns = [
    path('', views.home, name='home'),
    path('trees/', views.tree_list, name='tree_list'),
    path('trees/<int:tree_id>/', views.tree_detail, name='tree_detail'),
    path('equipment/', views.equipment_list, name='equipment_list'),
    path('equipment/<int:equipment_id>/', views.equipment_detail, name='equipment_detail'),
    path('purchase/<int:equipment_id>/', views.purchase_equipment, name='purchase_equipment'),
    path('plant/<int:tree_id>/', views.plant_tree, name='plant_tree'),
    path('select-location/<int:tree_id>/', views.select_location_for_tree, name='select_location_for_tree'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('my-trees/', views.my_trees, name='my_trees'),
    path('plant-at-location/<int:tree_id>/<int:location_id>/', views.plant_tree_at_location, name='plant_tree_at_location'),
    path('profile/', views.user_profile, name='user_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('news/', views.news_list, name='news_list'),
    path('search/', views.search_results, name='search_results'),
    path('community/', views.community, name='community'),
    path('about/', views.about, name='about'),
    path('my-trees/', views.my_trees, name='my_trees'),
    path('profile/', views.user_profile, name='user_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('news/', views.news_list, name='news_list'),
    path('search/', views.search_results, name='search_results'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('confirm-location/<int:tree_id>/<int:location_id>/', views.confirm_location, name='confirm_location'),
    path('plant/<int:tree_id>/<int:location_id>/', views.plant_tree, name='plant_tree'),
    path('payment/success/<int:tree_id>/', views.payment_success, name='payment_success'),
    path('equipment/select-address/<int:equipment_id>/', views.select_address, name='select_address'),
    path('equipment/payment/<int:equipment_id>/', views.equipment_payment, name='equipment_payment'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('trees/', views.tree_list, name='tree_list'),
    path('equipments/', views.equipment_list, name='equipment_list'),
    path('news/', views.news_list, name='news_list'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('about/', views.about, name='about'),
    path('search/', views.search_results, name='search_results'),
    path('login/', auth_views.LoginView.as_view(template_name='myapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('planting-plan/', views.planting_plan, name='planting_plan'),
    path('add-to-cart/<str:item_type>/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<str:item_type>/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-cart/<str:item_type>/<int:item_id>/', views.update_cart, name='update_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('start-planting/', views.start_planting_redirect, name='start_planting_redirect'),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('lockout/', TemplateView.as_view(template_name='lockout.html'), name='account_lockout'),
    path('process-cart/', views.process_cart_items, name='process_cart_items'),
    path('confirm-cart/', views.split_cart_confirmation, name='split_cart_confirmation')
    
]