# Generated by Django 5.1.6 on 2025-05-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='oorder_number',
            new_name='order_number',
        ),
    ]
