# Generated by Django 5.1.6 on 2025-05-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_purchase_status_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
