# Generated by Django 5.1.6 on 2025-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tree_is_recommended_alter_tree_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tree',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trees/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
