# Generated by Django 5.1.6 on 2025-04-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_tree_image_url_tree_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='image',
        ),
        migrations.AddField(
            model_name='tree',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
