# Generated by Django 5.1.6 on 2025-04-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_tree_image_tree_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='average_rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='tree',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tree',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
