# Generated by Django 5.1.6 on 2025-05-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_purchase_status_treepaymentproof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplanting',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='userplanting',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userplanting',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='tree_slips/'),
        ),
        migrations.AddField(
            model_name='userplanting',
            name='status',
            field=models.CharField(choices=[('verifying', 'กำลังตรวจสอบ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'ปลูกสำเร็จแล้ว')], default='verifying', max_length=20),
        ),
        migrations.DeleteModel(
            name='TreePaymentProof',
        ),
    ]
