# Generated by Django 5.1.6 on 2025-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_userplanting_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image_url',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
