# Generated by Django 5.1.6 on 2025-05-17 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_purchase_is_paid_alter_purchase_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.TextField(default='ไม่มีข้อมูล'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='ไม่มีข้อมูล', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('confirmed', 'ชำระเงินแล้ว'), ('expired', 'หมดอายุ')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tel',
            field=models.CharField(default='ไม่ระบุ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip', models.ImageField(upload_to='slips/')),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
