# Generated by Django 5.1.6 on 2025-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_purchase_date_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('preparing', 'กำลังจัดเตรียม'), ('shipping', 'กำลังจัดส่ง'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิกแล้ว')], default='pending', max_length=50),
        ),
    ]
